-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [quad_voter_proof]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace quad_voter_proof

/-- Trait implementation: [core::array::equality::{impl core::cmp::PartialEq<[U; N]> for [T; N]}]
    Source: '/rustc/library/core/src/array/equality.rs', lines 5:0-7:28
    Name pattern: [core::cmp::PartialEq<[@T; @N], [@U; @N]>] -/
@[reducible, rust_trait_impl "core::cmp::PartialEq<[@T; @N], [@U; @N]>"]
def Array.Insts.CoreCmpPartialEqArray {T : Type} {U : Type} (N : Std.Usize)
  (cmpPartialEqInst : core.cmp.PartialEq T U) : core.cmp.PartialEq (Array T N)
  (Array U N) := {
  eq := core.array.equality.PartialEqArray.eq cmpPartialEqInst
}

/-- [quad_voter_proof::StepResult]
    Source: 'src/lib.rs', lines 71:0-142:1
    Visibility: public -/
@[discriminant isize]
inductive StepResult where
| Agreed : Std.U64 → Array Bool 4#usize → StepResult
| Majority : Std.U64 → Std.U8 → Array Bool 4#usize → StepResult
| Undetermined : Array Bool 4#usize → StepResult
| OutsideHypothesis : Array Bool 4#usize → StepResult
| NoActiveChannels : Array Bool 4#usize → StepResult

/-- [quad_voter_proof::{impl core::clone::Clone for quad_voter_proof::StepResult}::clone]:
    Source: 'src/lib.rs', lines 69:9-69:14
    Visibility: public -/
def StepResult.Insts.CoreCloneClone.clone
  (self : StepResult) : Result StepResult := do
  ok self

/-- Trait implementation: [quad_voter_proof::{impl core::clone::Clone for quad_voter_proof::StepResult}]
    Source: 'src/lib.rs', lines 69:9-69:14 -/
@[reducible]
def StepResult.Insts.CoreCloneClone : core.clone.Clone StepResult := {
  clone := StepResult.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [quad_voter_proof::{impl core::marker::Copy for quad_voter_proof::StepResult}]
    Source: 'src/lib.rs', lines 69:16-69:20 -/
@[reducible]
def StepResult.Insts.CoreMarkerCopy : core.marker.Copy StepResult := {
  cloneInst := StepResult.Insts.CoreCloneClone
}

/-- Trait implementation: [quad_voter_proof::{impl core::marker::StructuralPartialEq for quad_voter_proof::StepResult}]
    Source: 'src/lib.rs', lines 69:22-69:31 -/
@[reducible]
def StepResult.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq StepResult := {
}

/-- [quad_voter_proof::{impl core::cmp::PartialEq<quad_voter_proof::StepResult> for quad_voter_proof::StepResult}::eq]:
    Source: 'src/lib.rs', lines 69:22-69:31
    Visibility: public -/
def StepResult.Insts.CoreCmpPartialEqStepResult.eq
  (self : StepResult) (other : StepResult) : Result Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | StepResult.Agreed __self_0 __self_1 =>
      match other with
      | StepResult.Agreed __arg1_0 __arg1_1 =>
        let b ← lift (core.cmp.impls.PartialEqU64.eq __self_0 __arg1_0)
        if b
        then
          core.array.equality.PartialEqArray.eq core.cmp.PartialEqBool __self_1
            __arg1_1
        else ok false
      | StepResult.Majority _ _ _ => fail panic
      | StepResult.Undetermined _ => fail panic
      | StepResult.OutsideHypothesis _ => fail panic
      | StepResult.NoActiveChannels _ => fail panic
    | StepResult.Majority __self_0 __self_1 __self_2 =>
      match other with
      | StepResult.Agreed _ _ => fail panic
      | StepResult.Majority __arg1_0 __arg1_1 __arg1_2 =>
        let b ← lift (core.cmp.impls.PartialEqU8.eq __self_1 __arg1_1)
        if b
        then
          let b1 ← lift (core.cmp.impls.PartialEqU64.eq __self_0 __arg1_0)
          if b1
          then
            core.array.equality.PartialEqArray.eq core.cmp.PartialEqBool
              __self_2 __arg1_2
          else ok false
        else ok false
      | StepResult.Undetermined _ => fail panic
      | StepResult.OutsideHypothesis _ => fail panic
      | StepResult.NoActiveChannels _ => fail panic
    | StepResult.Undetermined __self_0 =>
      match other with
      | StepResult.Agreed _ _ => fail panic
      | StepResult.Majority _ _ _ => fail panic
      | StepResult.Undetermined __arg1_0 =>
        core.array.equality.PartialEqArray.eq core.cmp.PartialEqBool __self_0
          __arg1_0
      | StepResult.OutsideHypothesis _ => fail panic
      | StepResult.NoActiveChannels _ => fail panic
    | StepResult.OutsideHypothesis __self_0 =>
      match other with
      | StepResult.Agreed _ _ => fail panic
      | StepResult.Majority _ _ _ => fail panic
      | StepResult.Undetermined _ => fail panic
      | StepResult.OutsideHypothesis __arg1_0 =>
        core.array.equality.PartialEqArray.eq core.cmp.PartialEqBool __self_0
          __arg1_0
      | StepResult.NoActiveChannels _ => fail panic
    | StepResult.NoActiveChannels __self_0 =>
      match other with
      | StepResult.Agreed _ _ => fail panic
      | StepResult.Majority _ _ _ => fail panic
      | StepResult.Undetermined _ => fail panic
      | StepResult.OutsideHypothesis _ => fail panic
      | StepResult.NoActiveChannels __arg1_0 =>
        core.array.equality.PartialEqArray.eq core.cmp.PartialEqBool __self_0
          __arg1_0
  else ok false

/-- Trait implementation: [quad_voter_proof::{impl core::cmp::PartialEq<quad_voter_proof::StepResult> for quad_voter_proof::StepResult}]
    Source: 'src/lib.rs', lines 69:22-69:31 -/
@[reducible]
def StepResult.Insts.CoreCmpPartialEqStepResult : core.cmp.PartialEq StepResult
  StepResult := {
  eq := StepResult.Insts.CoreCmpPartialEqStepResult.eq
}

/-- [quad_voter_proof::{impl core::cmp::Eq for quad_voter_proof::StepResult}::assert_fields_are_eq]:
    Source: 'src/lib.rs', lines 69:33-69:35
    Visibility: public -/
def StepResult.Insts.CoreCmpEq.assert_fields_are_eq
  (self : StepResult) : Result Unit := do
  ok ()

/-- Trait implementation: [quad_voter_proof::{impl core::cmp::Eq for quad_voter_proof::StepResult}]
    Source: 'src/lib.rs', lines 69:33-69:35 -/
@[reducible]
def StepResult.Insts.CoreCmpEq : core.cmp.Eq StepResult := {
  partialEqInst := StepResult.Insts.CoreCmpPartialEqStepResult
  assert_fields_are_eq := StepResult.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [quad_voter_proof::disable]:
    Source: 'src/lib.rs', lines 149:0-160:1 -/
def disable
  (active : Array Bool 4#usize) (index : Std.U8) :
  Result (Array Bool 4#usize)
  := do
  if index = 0#u8
  then Array.update active 0#usize false
  else
    if index = 1#u8
    then Array.update active 1#usize false
    else
      if index = 2#u8
      then Array.update active 2#usize false
      else Array.update active 3#usize false

/-- [quad_voter_proof::pair_step]:
    Source: 'src/lib.rs', lines 163:0-172:1 -/
def pair_step
  (wa : Std.U64) (wb : Std.U64) (active : Array Bool 4#usize) :
  Result StepResult
  := do
  if wa = wb
  then ok (StepResult.Agreed wa active)
  else ok (StepResult.Undetermined active)

/-- [quad_voter_proof::triple_step]:
    Source: 'src/lib.rs', lines 184:0-226:1 -/
def triple_step
  (ia : Std.U8) (wa : Std.U64) (ib : Std.U8) (wb : Std.U64) (ic : Std.U8)
  (wc : Std.U64) (active : Array Bool 4#usize) :
  Result StepResult
  := do
  if wa = wb
  then
    if wa = wc
    then
      if wb = wc
      then ok (StepResult.Agreed wa active)
      else ok (StepResult.OutsideHypothesis active)
    else
      if wb = wc
      then ok (StepResult.OutsideHypothesis active)
      else let a ← disable active ic
           ok (StepResult.Majority wa ic a)
  else
    if wa = wc
    then
      if wb = wc
      then ok (StepResult.OutsideHypothesis active)
      else let a ← disable active ib
           ok (StepResult.Majority wa ib a)
    else
      if wb = wc
      then let a ← disable active ia
           ok (StepResult.Majority wb ia a)
      else ok (StepResult.OutsideHypothesis active)

/-- [quad_voter_proof::quad_step]:
    Source: 'src/lib.rs', lines 233:0-281:1 -/
def quad_step
  (words : Array Std.U64 4#usize) (active : Array Bool 4#usize) :
  Result StepResult
  := do
  let w0 ← Array.index_usize words 0#usize
  let w1 ← Array.index_usize words 1#usize
  let w2 ← Array.index_usize words 2#usize
  let w3 ← Array.index_usize words 3#usize
  if w0 = w1
  then
    if w0 = w2
    then
      if w0 = w3
      then ok (StepResult.Agreed w0 active)
      else let a ← disable active 3#u8
           ok (StepResult.Majority w0 3#u8 a)
    else
      if w0 = w3
      then let a ← disable active 2#u8
           ok (StepResult.Majority w0 2#u8 a)
      else ok (StepResult.OutsideHypothesis active)
  else
    if w0 = w2
    then
      if w0 = w3
      then let a ← disable active 1#u8
           ok (StepResult.Majority w0 1#u8 a)
      else ok (StepResult.OutsideHypothesis active)
    else
      if w0 = w3
      then ok (StepResult.OutsideHypothesis active)
      else
        if w1 = w2
        then
          if w1 = w3
          then
            if w2 = w3
            then
              let a ← disable active 0#u8
              ok (StepResult.Majority w1 0#u8 a)
            else ok (StepResult.OutsideHypothesis active)
          else ok (StepResult.OutsideHypothesis active)
        else ok (StepResult.OutsideHypothesis active)

/-- [quad_voter_proof::step]:
    Source: 'src/lib.rs', lines 336:0-371:1
    Visibility: public -/
def step
  (active : Array Bool 4#usize) (words : Array Std.U64 4#usize) :
  Result StepResult
  := do
  let a0 ← Array.index_usize active 0#usize
  let a1 ← Array.index_usize active 1#usize
  let a2 ← Array.index_usize active 2#usize
  let a3 ← Array.index_usize active 3#usize
  if a0
  then
    if a1
    then
      if a2
      then
        if a3
        then quad_step words active
        else
          let i ← Array.index_usize words 0#usize
          let i1 ← Array.index_usize words 1#usize
          let i2 ← Array.index_usize words 2#usize
          triple_step 0#u8 i 1#u8 i1 2#u8 i2 active
      else
        if a3
        then
          let i ← Array.index_usize words 0#usize
          let i1 ← Array.index_usize words 1#usize
          let i2 ← Array.index_usize words 3#usize
          triple_step 0#u8 i 1#u8 i1 3#u8 i2 active
        else
          let i ← Array.index_usize words 0#usize
          let i1 ← Array.index_usize words 1#usize
          pair_step i i1 active
    else
      if a2
      then
        if a3
        then
          let i ← Array.index_usize words 0#usize
          let i1 ← Array.index_usize words 2#usize
          let i2 ← Array.index_usize words 3#usize
          triple_step 0#u8 i 2#u8 i1 3#u8 i2 active
        else
          let i ← Array.index_usize words 0#usize
          let i1 ← Array.index_usize words 2#usize
          pair_step i i1 active
      else
        if a3
        then
          let i ← Array.index_usize words 0#usize
          let i1 ← Array.index_usize words 3#usize
          pair_step i i1 active
        else
          let i ← Array.index_usize words 0#usize
          ok (StepResult.Agreed i active)
  else
    if a1
    then
      if a2
      then
        if a3
        then
          let i ← Array.index_usize words 1#usize
          let i1 ← Array.index_usize words 2#usize
          let i2 ← Array.index_usize words 3#usize
          triple_step 1#u8 i 2#u8 i1 3#u8 i2 active
        else
          let i ← Array.index_usize words 1#usize
          let i1 ← Array.index_usize words 2#usize
          pair_step i i1 active
      else
        if a3
        then
          let i ← Array.index_usize words 1#usize
          let i1 ← Array.index_usize words 3#usize
          pair_step i i1 active
        else
          let i ← Array.index_usize words 1#usize
          ok (StepResult.Agreed i active)
    else
      if a2
      then
        if a3
        then
          let i ← Array.index_usize words 2#usize
          let i1 ← Array.index_usize words 3#usize
          pair_step i i1 active
        else
          let i ← Array.index_usize words 2#usize
          ok (StepResult.Agreed i active)
      else
        if a3
        then
          let i ← Array.index_usize words 3#usize
          ok (StepResult.Agreed i active)
        else ok (StepResult.NoActiveChannels active)

end quad_voter_proof
